#!/bin/bash

# This script handles rotation of the screen and related input devices automatically
# using the output of the monitor-sensor command (part of the iio-sensor-proxy package).
# The target screen and input device names should be configured in the below variables.
# Note: input devices using the libinput driver (e.g. touchscreens) should be included
# in the XINPUT array.  Input devices using the Wacom driver should be included in the
# WACOM array.
#
# You can get a list of input devices with the `xinput` command.
# If you are uncertain which driver an input device is using, check the Xorg log.

#Mode - 1 - rotate all orientations; 0 - don't rotate portrait, only landscape
MODE=0

#Screen below for modesetting driver only
#SCREEN="eDP-1"
SCREEN="eDP1"

XINPUT=("Wacom Pen and multitouch sensor Finger")
#"Wacom Pen and multitouch sensor Pen Pen (0x9cd1aed8)" - if using XINPUT for stylus
WACOM=("Wacom Pen and multitouch sensor Pen stylus"
        "Wacom Pen and multitouch sensor Pen eraser")

#uses the values output by monitor-sensor to call the rotate function
function rotate_ms {
    case $1 in
        "normal")
            rotate 0
            ;;
        "right-up")
            rotate 1
            ;;
        "bottom-up")
            rotate 2
            ;;
        "left-up")
            rotate 3
            ;;
    esac
}

function rotate {

    if [[ ( "$MODE" -eq 0 ) && ( "$1" -eq 1 || "$1" -eq 3 ) ]] ; then
        return 0
    fi

    O_NAMES=("normal" "right" "inverted" "left")
    COORDS=("1, 0, 0, 0, 1, 0, 0, 0, 1" "0, 1, 0, -1, 0, 1, 0, 0, 1" "-1, 0, 1, 0, -1, 1, 0, 0, 1" "0, -1, 1, 1, 0, 0, 0, 0, 1")
    W_NAMES=("none" "cw" "half" "ccw")
    O_NO=$1

    TARGET_ORIENTATION=${O_NAMES[$O_NO]}

    echo "Rotating to" $TARGET_ORIENTATION

    #Rotate the screen
    xrandr --output $SCREEN --rotate $TARGET_ORIENTATION

    #Rotate libinput driver input devices
    for i in "${XINPUT[@]}" 
    do
        xinput --set-prop "$i" "Coordinate Transformation Matrix" ${COORDS[$O_NO]}
    done

    #Rotate Wacom driver input devices
    for i in "${WACOM[@]}"
    do
        xsetwacom set "$i" rotate ${W_NAMES[$O_NO]}
    done

}

while IFS='$\n' read -r line; do
    rotation="$(echo $line | sed -En "s/^.*orientation changed: (.*)/\1/p")"
    [[ !  -z  $rotation  ]] && rotate_ms $rotation
done < <(stdbuf -oL monitor-sensor)
